#!/bin/bash

set -e

cf --version
echo "Downloading Edge Build of the cf cli..."
curl -LsS http://go-cli.s3.amazonaws.com/master/cf-darwin-amd64.tgz > ~/Downloads/cfcli.tgz
tar xvzfC ~/Downloads/cfcli.tgz ~/Downloads/
echo "Installing cf to /usr/local/bin..."
rm ~/Downloads/cfcli.tgz
mv ~/Downloads/cf /usr/local/bin
echo "Done."
cf --version