#!/bin/bash

gcf --version
cd ~/Downloads
echo "Downloading Edge Build..."
curl -sS http://go-cli.s3.amazonaws.com/gcf-darwin-amd64.tgz > cfcli.tgz
tar xjf cfcli.tgz
echo "Installing gcf to /usr/local/bin..."
rm cfcli.tgz
mv gcf /usr/local/bin
cd ~
echo "Done."
gcf --version