#!/bin/bash

echo "Setting useful environmental variables..."
export CF_TRACE=~/tmp/cf_trace.txt
echo ""

echo "Installing useful scripts..."
cp ~/workspace/testapps/shell-scripts/cf-update /usr/local/bin
echo ""

echo "Updating cf to edge..."
cf-update
echo ""

echo "Okay, let's go!"